server:
  port: 8003

dubbo:
  protocol:
    name: dubbo
    threads: 100
    port: 30006
  application:
    name: dubbo-zookeeper-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  provider:
    timeout: 180000
    group: dubbo-provider-group